#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/html
echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
