#!/usr/bin/env bash
# installs a nginx with redirection
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
variable="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "19i $variable" /etc/nginx/sites-available/default
sudo service nginx restart
