#!/usr/bin/env bash
# installs a nginx with redirection
url="https://www.youtube.com/watch?v=7C9EYka6fIU"
var="rewrite ^/redirect_me $url permanent;"
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i "19i $var" /etc/nginx/sites-available/default
echo "Ceci n\'est pas une page." > /var/www/html/custom_404.html
sed -i '19i error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
