#!/usr/bin/env bash
# bash script that configures HAproxy 
# and send traffic to web-01 and web-02
apt-get update
apt-get -y install haproxy=1.6.\*
echo "frontend web_front
   bind *:80
   mode http
   default_backend web_back
   backend web_back
   balance roundrobin
   server web1 35.231.144.101:80 check
   server web2 34.229.74.97:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
