#!/usr/bin/env bash
# This script Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving 
# a SIGQUIT or SIGTERM signal
file=/var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid
trap "echo I hate the kill command; rm $file; exit" 15
trap "echo Y U no love me?!" 2
trap "rm $file" 3
i=1
while (( i > 0 ))
do 
  echo "To infinity and beyond"
  sleep 3
done

