#!/usr/bin/env bash
# This Bash script displays the time
# display hours from 0 to 12
# display minutes from 1 to 59
for (( i = 0; i <= 12; i++))
do
    echo "Hour:" $i
    for (( j = 0; j <= 59; j++))
    do
      echo $j
    done
done 
