#!/usr/bin/env bash
# Bash script that configures the container to 
# run as nginx user and  must be listening on all
# active IPs on port 8080
sudo chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
